import type { User, Lead, AppSettings } from './types';
import { DEFAULT_CHECKLIST } from './types';
import { generateId } from './utils';

const now = new Date();
const d = (daysAgo: number): Date => new Date(now.getTime() - daysAgo * 86400000);
const ahead = (days: number): Date => new Date(now.getTime() + days * 86400000);

export const MOCK_USERS: User[] = [
    {
        id: 'user-1',
        name: 'Admin certiBR',
        email: 'admin@certibr.com.br',
        password: 'admin123',
        role: 'admin',
        phone: '2197514xxxx',
        active: true,
        createdAt: d(120),
    },
    {
        id: 'user-2',
        name: 'Ana Costa',
        email: 'ana@certibr.com.br',
        password: 'ana123',
        role: 'consultor',
        phone: '21999990002',
        active: true,
        createdAt: d(90),
    },
    {
        id: 'user-3',
        name: 'Carlos Lima',
        email: 'carlos@certibr.com.br',
        password: 'carlos123',
        role: 'consultor',
        phone: '21999990003',
        active: true,
        createdAt: d(60),
    },
];

const mkChecklist = (checkedKeys: string[] = []) =>
    DEFAULT_CHECKLIST.map((item) => ({
        ...item,
        checked: checkedKeys.includes(item.key),
        checkedAt: checkedKeys.includes(item.key) ? d(2) : undefined,
    }));

export const MOCK_LEADS: Lead[] = [
    {
        id: 'lead-1',
        name: 'Fernanda Melo',
        whatsapp: '21988881001',
        email: 'fernanda@email.com',
        personType: 'cnpj',
        certificateType: 'ecnpj_a1',
        mainUse: 'Emitir nota fiscal',
        urgency: 'semana',
        origin: 'quiz',
        status: 'novo',
        assignedToId: 'user-2',
        createdAt: d(0),
        updatedAt: d(0),
        quizAnswers: {
            tipo: 'Empresa / CNPJ',
            uso: 'Emitir nota fiscal',
            situacao: 'Não, será o primeiro',
            urgencia: 'Preciso essa semana',
        },
        notes: [],
        activities: [
            {
                id: generateId(),
                leadId: 'lead-1',
                userId: 'system',
                type: 'criado',
                description: 'Lead criado via quiz da landing page',
                createdAt: d(0),
            },
        ],
        checklist: mkChecklist(),
    },
    {
        id: 'lead-2',
        name: 'Ricardo Oliveira',
        whatsapp: '11988882002',
        email: 'ricardo@empresa.com.br',
        cpfCnpj: '12.345.678/0001-90',
        personType: 'cnpj',
        certificateType: 'ecnpj_a1',
        mainUse: 'Acessar Receita Federal / e-CAC',
        urgency: 'hoje',
        origin: 'site',
        status: 'em_atendimento',
        assignedToId: 'user-2',
        createdAt: d(3),
        updatedAt: d(1),
        lastContactAt: d(1),
        nextFollowUpAt: ahead(1),
        nextFollowUpNote: 'Verificar se enviou os documentos',
        notes: [
            {
                id: 'note-1',
                leadId: 'lead-2',
                userId: 'user-2',
                content:
                    'Cliente entrou em contato pelo WhatsApp. Explicado o processo e solicitados os documentos.',
                createdAt: d(1),
            },
        ],
        activities: [
            { id: generateId(), leadId: 'lead-2', userId: 'system', type: 'criado', description: 'Lead criado via site', createdAt: d(3) },
            { id: generateId(), leadId: 'lead-2', userId: 'user-2', type: 'status_alterado', description: 'Status alterado de "Novo lead" para "Em atendimento"', createdAt: d(2) },
            { id: generateId(), leadId: 'lead-2', userId: 'user-2', type: 'retorno_agendado', description: `Retorno agendado para ${ahead(1).toLocaleDateString('pt-BR')}`, createdAt: d(1) },
        ],
        checklist: mkChecklist(),
    },
    {
        id: 'lead-3',
        name: 'Patrícia Souza',
        whatsapp: '21977773003',
        personType: 'cpf',
        certificateType: 'ecpf_a1',
        mainUse: 'Assinar documentos',
        urgency: 'semana',
        origin: 'instagram',
        status: 'aguardando_documentos',
        assignedToId: 'user-3',
        createdAt: d(5),
        updatedAt: d(2),
        lastContactAt: d(2),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-3', userId: 'system', type: 'criado', description: 'Lead criado via Instagram', createdAt: d(5) },
            { id: generateId(), leadId: 'lead-3', userId: 'user-3', type: 'status_alterado', description: 'Status alterado para "Em atendimento"', createdAt: d(4) },
            { id: generateId(), leadId: 'lead-3', userId: 'user-3', type: 'status_alterado', description: 'Status alterado para "Aguardando documentos"', createdAt: d(2) },
        ],
        checklist: mkChecklist(),
    },
    {
        id: 'lead-4',
        name: 'Marcos Costa',
        whatsapp: '31988884004',
        cpfCnpj: '123.456.789-01',
        personType: 'cpf',
        certificateType: 'ecpf_a1',
        mainUse: 'Meu contador pediu',
        urgency: 'semana',
        origin: 'indicacao',
        status: 'aguardando_pagamento',
        assignedToId: 'user-2',
        createdAt: d(8),
        updatedAt: d(3),
        lastContactAt: d(3),
        notes: [
            {
                id: 'note-2',
                leadId: 'lead-4',
                userId: 'user-2',
                content: 'Documentos recebidos e conferidos. Link de pagamento enviado.',
                createdAt: d(3),
            },
        ],
        activities: [
            { id: generateId(), leadId: 'lead-4', userId: 'system', type: 'criado', description: 'Lead criado por indicação', createdAt: d(8) },
            { id: generateId(), leadId: 'lead-4', userId: 'user-2', type: 'status_alterado', description: 'Status alterado para "Em atendimento"', createdAt: d(7) },
            { id: generateId(), leadId: 'lead-4', userId: 'user-2', type: 'status_alterado', description: 'Status alterado para "Aguardando documentos"', createdAt: d(5) },
            { id: generateId(), leadId: 'lead-4', userId: 'user-2', type: 'status_alterado', description: 'Status alterado para "Aguardando pagamento"', createdAt: d(3) },
        ],
        checklist: mkChecklist(['doc_pessoal', 'cpf_cnpj_conferido', 'comprovante_dados']),
    },
    {
        id: 'lead-5',
        name: 'Juliana Torres',
        whatsapp: '11977775005',
        cpfCnpj: '45.678.901/0001-23',
        personType: 'cnpj',
        certificateType: 'nfe_a1',
        mainUse: 'Emitir nota fiscal',
        urgency: 'hoje',
        origin: 'google_ads',
        status: 'pagamento_confirmado',
        assignedToId: 'user-3',
        createdAt: d(10),
        updatedAt: d(1),
        lastContactAt: d(1),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-5', userId: 'system', type: 'criado', description: 'Lead criado via Google Ads', createdAt: d(10) },
            { id: generateId(), leadId: 'lead-5', userId: 'user-3', type: 'status_alterado', description: 'Status alterado para "Pagamento confirmado"', createdAt: d(1) },
        ],
        checklist: mkChecklist(['doc_pessoal', 'cpf_cnpj_conferido', 'contrato_social', 'comprovante_dados', 'pagamento_confirmado']),
    },
    {
        id: 'lead-6',
        name: 'Bruno Almeida',
        whatsapp: '21966666006',
        cpfCnpj: '78.901.234/0001-56',
        personType: 'cnpj',
        certificateType: 'ecnpj_a1',
        mainUse: 'Acessar Receita Federal / e-CAC',
        urgency: 'hoje',
        origin: 'whatsapp',
        status: 'em_emissao',
        assignedToId: 'user-2',
        createdAt: d(12),
        updatedAt: d(0),
        lastContactAt: d(0),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-6', userId: 'system', type: 'criado', description: 'Lead criado via WhatsApp', createdAt: d(12) },
            { id: generateId(), leadId: 'lead-6', userId: 'user-2', type: 'status_alterado', description: 'Status alterado para "Em emissão"', createdAt: d(0) },
        ],
        checklist: mkChecklist(['doc_pessoal', 'cpf_cnpj_conferido', 'contrato_social', 'comprovante_dados', 'pagamento_confirmado', 'dados_enviados_parceiro']),
    },
    {
        id: 'lead-7',
        name: 'Carla Rodrigues',
        whatsapp: '21955557007',
        cpfCnpj: '987.654.321-09',
        personType: 'cpf',
        certificateType: 'ecpf_a1',
        mainUse: 'Advogada — assinar documentos',
        urgency: 'pesquisando',
        origin: 'indicacao',
        status: 'instalado',
        assignedToId: 'user-3',
        createdAt: d(30),
        updatedAt: d(15),
        lastContactAt: d(15),
        issuedAt: d(20),
        expiresAt: ahead(15),
        notes: [
            {
                id: 'note-3',
                leadId: 'lead-7',
                userId: 'user-3',
                content: 'Instalação concluída com sucesso. Cliente muito satisfeita.',
                createdAt: d(15),
            },
        ],
        activities: [
            { id: generateId(), leadId: 'lead-7', userId: 'system', type: 'criado', description: 'Lead criado por indicação', createdAt: d(30) },
            { id: generateId(), leadId: 'lead-7', userId: 'user-3', type: 'concluido', description: 'Certificado instalado — lead concluído', createdAt: d(15) },
            { id: generateId(), leadId: 'lead-7', userId: 'user-3', type: 'vencimento_registrado', description: `Vencimento: ${ahead(15).toLocaleDateString('pt-BR')}`, createdAt: d(15) },
        ],
        checklist: mkChecklist(DEFAULT_CHECKLIST.map((i) => i.key)),
    },
    {
        id: 'lead-8',
        name: 'Thiago Ferreira',
        whatsapp: '11944448008',
        personType: 'cnpj',
        certificateType: 'ecnpj_a1',
        mainUse: 'Emitir nota fiscal',
        urgency: 'pesquisando',
        origin: 'site',
        status: 'perdido',
        assignedToId: 'user-2',
        lostReason: 'preco',
        lostNote: 'Cliente achou o preço alto e preferiu outro fornecedor.',
        createdAt: d(20),
        updatedAt: d(10),
        lastContactAt: d(10),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-8', userId: 'system', type: 'criado', description: 'Lead criado via site', createdAt: d(20) },
            { id: generateId(), leadId: 'lead-8', userId: 'user-2', type: 'perdido', description: 'Marcado como perdido — Preço', createdAt: d(10) },
        ],
        checklist: mkChecklist(),
    },
    {
        id: 'lead-9',
        name: 'Simone Leal',
        whatsapp: '21933339009',
        cpfCnpj: '12.345.678/0001-01',
        personType: 'cnpj',
        certificateType: 'renovacao_a1',
        mainUse: 'Renovar certificado vencido',
        urgency: 'semana',
        origin: 'renovacao',
        status: 'renovacao_futura',
        assignedToId: 'user-3',
        createdAt: d(365),
        updatedAt: d(5),
        lastContactAt: d(5),
        issuedAt: d(360),
        expiresAt: ahead(7),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-9', userId: 'system', type: 'criado', description: 'Lead original criado', createdAt: d(365) },
            { id: generateId(), leadId: 'lead-9', userId: 'user-3', type: 'vencimento_registrado', description: `Alerta de renovação — vence em ${ahead(7).toLocaleDateString('pt-BR')}`, createdAt: d(5) },
        ],
        checklist: mkChecklist(),
    },
    {
        id: 'lead-10',
        name: 'Diego Santos',
        whatsapp: '19988880010',
        personType: 'cpf',
        certificateType: 'ecpf_a1',
        mainUse: 'Médico — assinar documentos',
        urgency: 'hoje',
        origin: 'google_ads',
        status: 'novo',
        createdAt: d(0),
        updatedAt: d(0),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-10', userId: 'system', type: 'criado', description: 'Lead criado via Google Ads', createdAt: d(0) },
        ],
        checklist: mkChecklist(),
    },
    {
        id: 'lead-11',
        name: 'Aline Barbosa',
        whatsapp: '31977771011',
        personType: 'cnpj',
        certificateType: 'ecnpj_a1',
        mainUse: 'Emitir nota fiscal',
        urgency: 'semana',
        origin: 'quiz',
        status: 'aguardando_documentos',
        assignedToId: 'user-2',
        createdAt: d(6),
        updatedAt: d(4),
        lastContactAt: d(4),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-11', userId: 'system', type: 'criado', description: 'Lead criado via quiz', createdAt: d(6) },
            { id: generateId(), leadId: 'lead-11', userId: 'user-2', type: 'status_alterado', description: 'Status alterado para "Aguardando documentos"', createdAt: d(4) },
        ],
        checklist: mkChecklist(),
    },
    {
        id: 'lead-12',
        name: 'Rafael Lima',
        whatsapp: '41966662012',
        cpfCnpj: '11.222.333/0001-44',
        personType: 'cnpj',
        certificateType: 'nfe_a1',
        mainUse: 'Emitir nota fiscal',
        urgency: 'hoje',
        origin: 'site',
        status: 'instalado',
        assignedToId: 'user-3',
        createdAt: d(45),
        updatedAt: d(30),
        lastContactAt: d(30),
        issuedAt: d(35),
        expiresAt: ahead(30),
        notes: [],
        activities: [
            { id: generateId(), leadId: 'lead-12', userId: 'system', type: 'criado', description: 'Lead criado via site', createdAt: d(45) },
            { id: generateId(), leadId: 'lead-12', userId: 'user-3', type: 'concluido', description: 'Certificado instalado', createdAt: d(30) },
        ],
        checklist: mkChecklist(DEFAULT_CHECKLIST.map((i) => i.key)),
    },
];

export const MOCK_SETTINGS: AppSettings = {
    companyName: 'certiBR',
    mainWhatsApp: '5521975140550',
    defaultAssigneeId: undefined,
    certificatePrices: {
        ecnpj_a1: 'Consultar',
        ecpf_a1: 'Consultar',
        nfe_a1: 'Consultar',
        renovacao_a1: 'Consultar',
    },
    messages: {
        initial:
            'Olá, {nome}! Vi que você tem interesse em um Certificado Digital A1. Vou te ajudar a escolher a melhor opção e seguir com o processo. 😊',
        documents:
            'Olá, {nome}! Para darmos continuidade ao seu Certificado Digital A1, preciso que envie os documentos solicitados. Assim que recebermos, seguimos com a emissão. 📄',
        payment:
            'Olá, {nome}! Segue a orientação para pagamento do seu Certificado Digital A1. Após a confirmação, damos continuidade ao processo. 💳',
        installation:
            'Olá, {nome}! Seu Certificado Digital A1 está pronto. Vamos te orientar na instalação e uso correto. 🎉',
        renewal:
            'Olá, {nome}! Seu Certificado Digital A1 vence em breve. Quer que eu te ajude com a renovação para evitar problemas na emissão de notas ou acesso aos sistemas? 🔄',
    },
};
